const cityDestinations = {
    ATL: "Atlanta",
    LAX: "Los Angeles",
    ORD: "Chicago",
    DFW: "Dallas/Fort Worth",
    DEN: "Denver",
    JFK: "New York",
    SFO: "San Francisco",
    SEA: "Seattle",
    MIA: "Miami",
    MCO: "Orlando",
    LHR: "London",
    CDG: "Paris",
    AMS: "Amsterdam",
    FRA: "Frankfurt",
    DXB: "Dubai",
    HND: "Tokyo",
    PEK: "Beijing",
    SIN: "Singapore",
    SYD: "Sydney",
    YYZ: "Toronto",
    ICN: "Seoul",
    HKG: "Hong Kong",
    BKK: "Bangkok",
    MUC: "Munich",
    MAD: "Madrid",
    IST: "Istanbul",
    DEL: "Delhi",
    PVG: "Shanghai",
    BCN: "Barcelona",
    ZRH: "Zurich",
    LGA: "New York",
    LGW: "London",
    TXL: "Berlin",
    BOS: "Boston",
    DUB: "Dublin",
    MNL: "Manila",
    KUL: "Kuala Lumpur",
    GRU: "Sao Paulo",
    EWR: "Newark",
    IAD: "Washington, D.C.",
    PHX: "Phoenix",
    CPH: "Copenhagen",
    CAI: "Cairo",
    MXP: "Milan",
    NRT: "Tokyo",
    ARN: "Stockholm",
    DOH: "Doha",
    VIE: "Vienna",
    MEL: "Melbourne",
    JNB: "Johannesburg",
    CTU: "Chengdu",
    BRU: "Brussels",
    HEL: "Helsinki",
    CUN: "Cancun",
    GVA: "Geneva",
    RUH: "Riyadh",
    TPE: "Taipei",
    MEX: "Mexico City",
    LAS: "Las Vegas",
    AKL: "Auckland",
    OSL: "Oslo",
    IAH: "Houston",
    CAN: "Guangzhou",
    PER: "Perth",
    LIS: "Lisbon",
    BOM: "Mumbai",
    PRG: "Prague",
    ATH: "Athens",
    DUS: "Düsseldorf",
    GIG: "Rio de Janeiro",
    SVO: "Moscow",
    CGK: "Jakarta",
    WAW: "Warsaw",
    BUD: "Budapest",
    LIM: "Lima",
    RIX: "Riga",
    TLL: "Tallinn",
    VCE: "Venice",
    CCU: "Kolkata",
    TSN: "Tianjin",
    YVR: "Vancouver",
    SHA: "Shanghai",
    ADD: "Addis Ababa",
    ADL: "Adelaide",
    CGN: "Cologne",
    PTY: "Panama City",
    EDI: "Edinburgh",
    DME: "Moscow",
    STO: "Stockholm",
    SCL: "Santiago",
    CPT: "Cape Town",
    LED: "Saint Petersburg",
    DCA: "Washington, D.C.",
    KIX: "Osaka",
    TAM: "Tampico",
    BNE: "Brisbane",
    BWI: "Baltimore",
    FCO: "Rome",
    MAN: "Manchester",
    CMN: "Casablanca",
    HNL: "Honolulu",
    BHX: "Birmingham",
    LYS: "Lyon",
    TLV: "Tel Aviv",
    HAM: "Hamburg",
    ORY: "Paris",
    NGO: "Nagoya",
    BGO: "Bergen",
    VNO: "Vilnius",
    NCE: "Nice",
    AGP: "Malaga",
    LUX: "Luxembourg",
    XMN: "Xiamen",
    MAA: "Chennai",
    DLC: "Dalian",
    CZM: "Cozumel",
    CLT: "Charlotte",
    KEF: "Reykjavik",
    PUS: "Busan",
    FLL: "Fort Lauderdale",
    MSY: "New Orleans",
    SJC: "San Jose",
    PDX: "Portland",
    SAN: "San Diego",
    RDU: "Raleigh/Durham",
    TPA: "Tampa",
    STL: "St. Louis",
    BOG: "Bogota",
    CMB: "Colombo",
    KWI: "Kuwait City",
    ISB: "Islamabad",
    DAC: "Dhaka",
    PHL: "Philadelphia",
    DTW: "Detroit"
};

export default cityDestinations;
